### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json
#Authorization: Bearer {{token}}

{
  "name": "John Doe Billing Account 17",
  "email": "john_doe_billing17@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1998-09-09",
  "registeredDate": "2025-11-28"
}

###