### Update a existing patient entity with id
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
#Authorization: Bearer {{token}}

{
  "name": "John Doe1",
  "email": "john.doe@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09"
}

###